-- SECURITY HARDENING MIGRATION
-- Generated by Security Audit

-- 1. Ensure RLS is enabled on ALL critical tables
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE generations ENABLE ROW LEVEL SECURITY;
ALTER TABLE system_prompts ENABLE ROW LEVEL SECURITY;
ALTER TABLE portfolio ENABLE ROW LEVEL SECURITY;

-- 2. HARDEN: System Prompts
-- Prevent regular users from modifying system prompts. Only read allowed (or restrict to admin if strict).
-- Dropping previous overly permissive policies
DROP POLICY IF EXISTS "Allow full access to authenticated users" ON system_prompts;
DROP POLICY IF EXISTS "Enable read access for all users" ON system_prompts;

-- New Policy: Read Only for Authenticated Users (so they can generate)
CREATE POLICY "Allow read access to authenticated users"
ON system_prompts
FOR SELECT
TO authenticated
USING (true);

-- New Policy: Write Access only for Service Role (Admins)
-- Note: Supabase Admin client bypasses RLS, so we don't strictly need a policy for it, 
-- but we explicitly DO NOT create a write policy for 'authenticated'.

-- 3. HARDEN: Profiles
-- Ensure users can only update their OWN profile
DROP POLICY IF EXISTS "Users can update own profile" ON profiles;
CREATE POLICY "Users can update own profile"
ON profiles
FOR UPDATE
TO authenticated
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

-- Ensure users can only read their own profile (or public parts? Depends on app)
-- Assuming public profile reading is handled by a separate policy or not needed for privacy.
-- If 'portfolio' is public, profiles might need to be partially public. 
-- For now, we stick to "Read Own" + Service Role.

-- 4. HARDEN: Generations/Leads
-- Users see only their own data
DROP POLICY IF EXISTS "Users view own generations" ON generations;
CREATE POLICY "Users view own generations"
ON generations
FOR SELECT
TO authenticated
USING (auth.uid() = organization_id); -- Assuming organization_id maps to auth.uid for personal tenants

DROP POLICY IF EXISTS "Users view own leads" ON leads;
CREATE POLICY "Users view own leads"
ON leads
FOR SELECT
TO authenticated
USING (auth.uid() = organization_id); 
